# Generated by Django 2.2 on 2021-06-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungrycritters', '0002_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
