# Generated by Django 2.2 on 2021-06-04 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210601_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 3, 20, 5, 27, 412382)),
        ),
    ]
